name: YouTube 24/7 Live

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          ffmpeg -re -stream_loop -1 -i live.mp4 \
          -c:v libx264 -preset veryfast -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p \
          -c:a aac -b:a 128k -ar 44100 -g 50 -f flv \
          "rtmp://a.rtmp.youtube.com/live2/berz-aujw-uzbs-v8zt-1m34"
